lib/marketplace_kit/services/api_driver.rb, lib/marketplace_kit/services/config.rb
In dockerized version, staging uses self-signed certificates, and such certificates fail p2p verification. I would like to disable this verification on non-production envs.
=> do not verify ssl on non-production env

marketplace-kit-archive.js, marketplace-kit-watch.js
In deploy:
Prevents deploying when there is no `marketplace_builder` and when it's empty.
In sync:
Prevents deploying when there is no `marketplace_builder` - better error message.
Fixes #53
=> Prevent deploying empty marketplace

lib/kit.js, lib/platformRequestHeaders.js, marketplace-kit-auth.js, marketplace-kit-deploy.js, marketplace-kit-env-add.js, marketplace-kit-logs.js, marketplace-kit-push.js, marketplace-kit-sync.js, marketplace-kit-watch.js, npm-shrinkwrap.json, package.json
=> PP-27 replace user temporary token with api key

lib/proxy.js, marketplace-kit-migrations-generate.js, marketplace-kit-migrations-run.js, marketplace-kit-migrations.js, marketplace-kit.js
Migrations can be used when you need to change the data or execute some piece of code outside of the regular application running cycle, for example when you want to seed data on each environment.
The first step for using a migration is generating it through `marketplace-kit migrations` command.
Example:
```sh
marketplace-kit migrations generate ENVIRONMENT MIGRATION_NAME
```
On success, this will generate an empty migration in `marketplace_builder/migrations` directory. 
Please notice that the name you provide will be prefixed with UTC timestamp, for example, looking like this: `20180731120002` this value is used to keep the migrations in order in all environments.
You can use the liquid markup in migration files - that includes executing GraphQL mutations (`execute_query` tag). …
=> Data migrations

marketplace-kit-archive.js, marketplace-kit-deploy.js, marketplace-kit-push.js, marketplace-kit-watch.js
Adds support for deploying/synchronizing public and private folders.
This will allow project structure to look the following way:
```sh
* marketplace_builder
* public
* private
* modules
* admin_cms
* public
* bootstrap_styles
* public
```
In the above example:
* `marketplace_builder` can be used as usual
* `public` can be used instead of `marketplace_builder` or by module creators in which case this is the place where they can put files visible to anyone using the plugin
* `private` those files will be visible only to module creator/owner they will get deployed to target instance by Partner Portal, but if a developer does a `marketplace-kit pull` he/she will only get `public` folder for the extension.
* `modules` this is where the installed extensions are placed in this example there are …
=> Add support for public and private folders

marketplace-kit-archive.js, marketplace-kit-watch.js
From now on we can only develop modules in the `/modules` directory. The separation to `public` and `private` folders inside `modules/modulename/` still works but top-level `public` and `private` are no longer allowed.
The reason for this change is that developing modules on top-level would require backend code to parse module and replace paths in includes of layouts correctly when the module was installed and this would be hard to do and error prone
=> Remove support for toplevel public and private dirs

marketplace-kit-push.js
The default is `stderr`. It's explained [here](https://github.com/sindresorhus/ora/issues/85#issuecomment-410576130) that:
> The reason it's stderr is so that it will not interfere with normal output. Most other spinners use stderr too.
I find this wrong, and since I use some mkit instrumentation I'd like to be able to say if there is something on `stderr` it means something went wrong along the way.
=> Change spinner to use stdout

marketplace-kit-archive.js, marketplace-kit-watch.js
Fix the issue when files included in modules outside of public or private folders are synced/deployed to the server. 
It will now be possible to have configuration files on that level for example:
```
ls modules/blog
private
public
src
package.json
```
=> ignore module files irrelevant for pOS

marketplace-kit-watch.js
For historical reasons, we don't send `marketplace_builder` in the path to backend when syncing but we still do need it when reading in the file
=> Use wholePath to read the file but send cleanedUpPath to the backend

lib/deployServiceClient.js, lib/proxy.js, marketplace-kit-deploy.js
Related PR: https://github.com/mdyd-dev/desksnearme/pull/8063
=> Assets manifest: use path instead of mtime; seperate assets per deploy

lib/data/uploadFiles.js
s3 is escaping filenames by itself but is returning unescaped url (containing spaces), hence we do send unescaped file name and escape returned link.
=> fix url problem after upload to S3

lib/templates.js, test/lib/templates.test.js
Before this was misbehaving by returning empty string, wipping out
some files by accident. 😳
=> When there is an error parsing a file return it's whole content

CHANGELOG.md, README.md, bin/pos-cli-data-clean.js, bin/pos-cli-data-export.js, bin/pos-cli-data-import.js, bin/pos-cli-data-update.js, bin/pos-cli-deploy.js, bin/pos-cli-env-add.js, bin/pos-cli-env-list.js, bin/pos-cli-env.js, bin/pos-cli-gui-serve.js, bin/pos-cli-gui.js, bin/pos-cli-logs.js, bin/pos-cli-migrations-generate.js, bin/pos-cli-migrations-list.js, bin/pos-cli-migrations-run.js, bin/pos-cli-modules-list.js, bin/pos-cli-modules-remove.js, bin/pos-cli-pull.js, bin/pos-cli-sync.js, lib/data/isValidJSON.js, lib/files.js, lib/settings.js, test/lib/files.test.js
This PR deprecates `.marketplace-kit` file in favor of `.pos`.
It looks for config in this order:
1. `CONFIG_FILE_PATH` env
2. `.pos`
3. `.marketplace-kit`
When adding new env it creates .pos.
It should work with all three variants, and if all files exist, it will respect the order above when adding new one.
QA steps:
* Adding & listing envs should work as usual
* Deploys should work
* Sync should work
* Listing modules & removing modules should work
=> Rename .marketplace-kit to .pos

lib/proxy.js
We need this header to be present in all authenticated requests.
=> Include header with domain name in all requests

bin/pos-cli-logs.js
When I logged variable that was empty I didn't get any log entries, even with custom error type
```liquid
{% log product_id, type: "foo" %}
```
=> Logs: display empty messages

bin/pos-cli-deploy.js
Since
```
params = {}
params.partialDeploy #=> undefined
```
db record created based on this params looked like this, if `--partial-deploy` was not set:
```options: {"force_mode"=>nil, "partial_deployment"=>"undefined", "sync"=>false}```
=> replace "undefined" with boolean"

lib/files.js, lib/shouldBeSynced.js, lib/watch.js, npm-shrinkwrap.json, package.json, test/fixtures/.posignore, test/lib/files.test.js
Adds support for `.posignore` file. When placed in root directory it will apply `.gitignore` style pattern matching to files and ignore them from syncing.
Main use case is the ability to have `node_modules` inside of `modules` folder that will not sync every JS file in there.
`.posignore` rules are not applied during deploy though, since as far as I can tell, it’s only matching folder names when building archive.  Might be worth to consider it in next iteration
=> Add support for .posignore file

CHANGELOG.md, README.md, bin/pos-cli-logs.js
Filter options for logs: 
```
payment-examples [payouts-rc●●] % pos-cli logs dev --filter DEBUG
[10:51:56] Starting live logging...
[2019-11-11 09:29:40.697Z] - DEBUG: TEST
[2019-11-11 09:29:40.703Z] - DEBUG: data
```
If you need to escape the chaos of all different types of logs left in the project.
=> add ability to filter logs by log type

lib/audit.js, lib/audit/duplicateFile.js, lib/audit/extensions.js
Only allow .liquid files in the following directories:
* forms
* form_configurations
* authorization_policies
* notifications
Only allow .yml files in the following directories:
* custom_model_types
* custom_model_schemas
* instance_profile_types
* instance_profile_schemas
Check for liquid files with the same partial paths.
Fixes #352.
Fixes #353.
=> Extension check audit in some directories

lib/data/waitForStatus.js
Reported by user:
```
TypeError: Cannot read property 'status' of undefined
at /opt/homebrew/lib/node_modules/@platformos/pos-cli/lib/data/waitForStatus.js:5:22
at tryCatcher (/opt/homebrew/lib/node_modules/@platformos/pos-cli/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/opt/homebrew/lib/node_modules/@platformos/pos-cli/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/opt/homebrew/lib/node_modules/@platformos/pos-cli/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/opt/homebrew/lib/node_modules/@platformos/pos-cli/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/opt/homebrew/lib/node_modules/@platformos/pos-cli/node_modules/bluebird/js/release/promise.js: …
```
=> Do not throw error when there is no status in waitForStatus

lib/ServerError.js, lib/apiRequest.js, lib/modules.js, test/modules-push.test.js
Any reason why this line was there and we're not treating these errors like the technical errors below? Alternatively I could add rejection handling code to various callers but first I wanted to explore this cleaner avenue.
This fix is to avoid unhandled top level rejections which break pos-cli and require a restart of pos-cli sync every time a few such errors occur (for example because of invalid syntax).
Thanks!
=> Avoid unhandled top level rejections which break sync

bin/pos-cli-env-add.js, lib/apiRequest.js, lib/data/waitForStatus.js, lib/environments.js, lib/modules/dependencies.js, lib/portal.js, lib/proxy.js, lib/utils/password.js
https://trello.com/c/QB4gfWv7/58-when-registering-via-oauth-the-tutorial-needs-the-full-command-to-authorize-the-instance-we-are-missing-the-token-parameter
=> Env add with authorization on portal website

CHANGELOG.md, bin/pos-cli-data-export.js
Changed the default option from string 'false' to false, otherwise it always exports as zip.
Thanks!
=> Fix for data export zip option

CHANGELOG.md, README.md, package.json
https://trello.com/c/VlyHPpxV/110-check-for-node-version-in-pos-cli-to-warn-about-old-version
It will give you an error when you try to install pos-cli on old node.
=> Set min node version

CHANGELOG.md, bin/pos-cli-modules-pull.js
=> fix error for pulling module which is not installed

gui/next/playwright/backgroundJobs.spec.js, gui/next/playwright/helpers/posInstance.js, gui/next/playwright/home.spec.js, gui/next/playwright/logs.spec.js, gui/next/playwright/logsv2.spec.js
Instead of using hardcoded CI instance to run tests, use the instance that is currently connected with `pos-cli gui serve`.
=> Run tests in context of currently connected instance

CHANGELOG.md, lib/server.js, package-lock.json, package.json
Since the server and client are on the same machine, gzip compression doesn't matter - it just wastes a little CPU power.
=> Remove compression

CHANGELOG.md, bin/pos-cli-modules-push.js, lib/modules.js, test/fixtures/modules/multiple_modules/modules/bar/template-values.json, test/fixtures/modules/multiple_modules/modules/foo/template-values.json, test/fixtures/modules/template_values_in_root_first/modules/foo/template-values.json, test/fixtures/modules/template_values_in_root_first/template-values.json, test/modules-push.test.js
Before this PR, when `pos-cli modules push --email <email>` is invoked, the code works as follows:
* Try to find the first `template-values.json` file which matches `modules/*/template-values.json`. (this is problematic if there are multiple template-values.json, which is the case if you download dependencies via pos-cli modules download, which also downloads template-values.json)
* If it's there, take the `machine_name` attribute from the file and create Zip Archive based on `modules/<machine_name>` (this is problematic if there's a mismatch between the directory name and the value inside template-values.json`)
* If it's not, find the `./template-values.json` from the current directory
* If it's there, archive the current directory (for backwards compatibility, some of the old modules …
=> improve finding the right template-values.json when pushing new module

bin/pos-cli-data-import.js, test/data.test.js
This is a fix for:
```
[21:29:16] 406 - {"errors":["param is missing or the value is empty: data"]}
```
Even if we had gotten the backend to look at the actual data, it would have been a JSON representation of a stream.
Thanks!
=> Fix for JSON contents not accessible for data import
