Platform-OS/pos-cli

README.md

Also fix some formatting issues in table.

Default flag - add readme note

---

lib/marketplace_kit/errors/api_error.rb
lib/marketplace_kit/services/api_driver.rb
lib/marketplace_kit/services/logger.rb
lib/marketplace_kit/version.rb

Proper error handling when authorization expires:
```
Builder error: Invalid Authentication
```

Issue #16 Unauthorized user api error

---

.eslintrc
lib/settings.js
marketplace-kit
marketplace-kit-archive
marketplace-kit-auth
marketplace-kit-deploy
marketplace-kit-env
marketplace-kit-env-add
marketplace-kit-env-list
marketplace-kit-push
marketplace-kit-sync
marketplace-kit-watch

Prettier removed couple () around arguments and changed couple quotes.

Reword help, rename endpoint -> environment

---

marketplace-kit.js
npm-shrinkwrap.json
package.json

Notify when new version of mpkit is available no npm

---

marketplace-kit-push.js

fix-deploy-force-mode

---

lib/validators/email.js
lib/validators/existence.js
lib/validators/index.js
lib/validators/url.js
marketplace-kit-auth.js
marketplace-kit-deploy.js
marketplace-kit-env-add.js
marketplace-kit-logs.js
marketplace-kit-push.js
marketplace-kit-sync.js
npm-shrinkwrap.json
package.json

Add validations for required arguments and email/url format

---

marketplace-kit-watch.js

**DIY-0000-throttle-sync-api-call**

DIY-0000-throttle-sync-api-call

---

lib/errors.js
marketplace-kit-deploy.js
marketplace-kit-push.js
marketplace-kit-watch.js

**allow-errors-be-more-informative**

allow-errors-be-more-informative

---

marketplace-kit-logs.js
marketplace-kit-watch.js
package.json

This reverts commit 7630624af099e69f19927ab048d94898c867d67c.

Revert "Remove unnecessary dependencies"

---

marketplace-kit-push.js

exit-1-on-deploy-failure

---

marketplace-kit-watch.js

1. Do not sync empty yml files - empty css/js/liquid files are valid, a lot of the times. We can go further down this road and make only empty partials valid
2. Inform user when file has not been synced becase of shouldSync validation failed
3.  Small refactor

Inform users when file is not synced. Add emptyYML validation

---

marketplace-kit-watch.js

Fix shouldbesynced issue

---

lib/dataTransform.js
lib/proxy.js
marketplace-kit-data-clean.js
marketplace-kit-data-export.js
marketplace-kit-data-import.js
marketplace-kit-data.js
marketplace-kit.js
npm-shrinkwrap.json
package.json

```
marketplace-kit data export
marketplace-kit data import
marketplace-kit data clean
```
For now it will work only with new stack. For old stack it is gonna display proper message.
DO NOT MERGE YETI

Data import export clean

---

marketplace-kit-push.js

fix-deploy

---

marketplace-kit.js
npm-shrinkwrap.json
package.json

https://github.com/yuanchuan/node-watch/issues/69

Update node-watch to version that fixes synx on linux; release data import, export, clean

---

marketplace-kit-deploy.js
marketplace-kit-push.js

**exit-with-1-code-on-push-failuer**

exit-with-1-code-on-push-failure

---

lib/audit/rules.js
marketplace-kit-audit.js

Improvements to MK audit 
```
audit_test % mk audit
[Audit Warn] deprectaed "title" tag in the following files:
marketplace_builder/views/pages/home.html.liquid
marketplace_builder/views/partials/layout/constants.liquid
marketplace_builder/views/partials/layout/head.liquid
[Audit Warn] deprecated "generate_url" filter in the following files:
marketplace_builder/form_configurations/test.liquid
[Audit Warn] deprecated argument "resource_id" of include_form tag, please replace with "id" in the following files:
marketplace_builder/views/pages/home.html.liquid
grep: no such file or directory: {marketplace_builder,modules/**}/{views/**/*.liquid
[Audit Warn] deprecated key "configuration", please replace with "fields" in the following files:
marketplace_builder/form_configurations/test.liquid …
```

audit improvements

---

marketplace-kit.js
npm-shrinkwrap.json
package.json
test/lib/commands.test.js

Missing command

---

.gitignore
lib/data/uploadFiles.js

As in the description - processing for user profile images/attachements in import

Add image processing to import of user profiles

---

package.json

Fixes https://github.com/mdyd-dev/marketplace-kit/issues/140

Add missing npm package

---

lib/deployServiceClient.js
lib/logger.js
marketplace-kit-deploy.js

Allow deploy assets directly to s3 and upload `assets.json` - manifest file to platform.
Still it uses long polling fallback due to problems with ELB.

Sockets sucs

---

marketplace-kit-init.js

There was hardcoded 'marketplace_builder' in init, so only that dir was copied when initializing. I replaced it with `*` which means modules are also copied.
This has a very positive side effect that i want to keep: it also copies package.json files etc.
https://asciinema.org/a/sadPxKAn550zb30T0NiggwZYh

unZip whole directory not only marketplace_builder

---

lib/templates.js
marketplace-kit-archive.js
marketplace-kit-watch.js
test/lib/templates.test.js

template per module

---

lib/templates.js
marketplace-kit-watch.js

Fix for images being altered by templating system in modules

[WIP] Fix processing binary files with mustache

---

lib/templates.js
test/lib/templates.test.js

It does not make much sense to process template if template data is missing.

Dont process template if there are no values

---

lib/data/fetchFiles.js
lib/data/uploadFiles.js
marketplace-kit-data-export.js
marketplace-kit-data-import.js
package.json

Also
Fixes: https://github.com/mdyd-dev/marketplace-kit/issues/128

Data export queue file upload download

---

gui/graphql/public/index.html
marketplace-kit-server.js

**add-connection-info-to-graphiql**

add-connection-info-to-graphiql

---

gui/graphql/public/index.html

**add-connection-info-to-graphiql-CR**

add-connection-info-to-graphiql-CR

---

marketplace-kit-push.js

**fix-error-on-deploy-failure**

fix-error-on-deploy-failure

---

lib/audit/rules.js
marketplace-kit-archive.js
marketplace-kit-audit.js
marketplace-kit-init.js
marketplace-kit-migrations-generate.js
marketplace-kit-pull.js
marketplace-kit-push.js
marketplace-kit-watch.js

support-app-directory-app-source-code-dir

---

gui/graphql/public/index.html
marketplace-kit-server.js

Improve graphiql css

---

bin/pos-cli-server.js

Inform user when port of gui serve is in use

---

README.md
bin/pos-cli-init.js
npm-shrinkwrap.json
package.json
test/lib/commands.test.js

Init degit

---

CHANGELOG.md
bin/pos-cli-deploy.js
bin/pos-cli-env-add.js
lib/portal.js
lib/presignUrl.js
npm-shrinkwrap.json
package.json

Fix deploy with direct assets upload.

Extract PP host

---

bin/pos-cli-env-add.js
lib/portal.js

Include URl of the doimain in the authentication request

Forward instance's domain url to PP

---

README.md

Fixes https://github.com/mdyd-dev/pos-cli/issues/237

Document missing commands

---

bin/pos-cli-data-clean.js
bin/pos-cli-data-export.js
bin/pos-cli-data-import.js
bin/pos-cli-data-update.js
bin/pos-cli-data.js
bin/pos-cli-deploy.js
bin/pos-cli-env-add.js
bin/pos-cli-env-list.js
bin/pos-cli-env.js
bin/pos-cli-gui-serve.js
bin/pos-cli-gui.js
bin/pos-cli-init.js
bin/pos-cli-logs.js
bin/pos-cli-migrations-generate.js
bin/pos-cli-migrations-list.js
bin/pos-cli-migrations-run.js
bin/pos-cli-migrations.js
bin/pos-cli-modules-list.js
bin/pos-cli-modules-remove.js
bin/pos-cli-modules.js
bin/pos-cli-pull.js
bin/pos-cli-sync.js
bin/pos-cli.js
test/lib/commands.test.js

Fix help message - command names

---

CHANGELOG.md
bin/pos-cli-audit.js
bin/pos-cli-init.js
bin/pos-cli-logs.js
bin/pos-cli-migrations-generate.js
lib/ServerError.js
lib/logger/report.js
npm-shrinkwrap.json
package.json

Add sentry

---

lib/files.js

Improve error handling for invalid json files

---

CHANGELOG.md
bin/pos-cli-push.js
lib/deploy/defaultStrategy.js
lib/deploy/directAssetsUploadStrategy.js
lib/proxy.js

More concrete info to the user, more info for us when it comes to debugging.

Improve server errors handling and communication

---

lib/portal.js

https://github.com/mdyd-dev/partner-portal/issues/612

New url to portal

---

bin/pos-cli-push.js

Fixes: https://github.com/mdyd-dev/desksnearme/issues/8680

Handle errors on failed deploy

---

test/audit.test.js
test/deploy.test.js
test/utils/cliPath.js

Windows: fix path to files

---

bin/pos-cli-env-list.js
test/lib/commands.test.js

Fix env list to not throw an error

---

lib/ServerError.js
lib/archive.js
lib/assets.js
lib/assets/packAssets.js
lib/deploy/directAssetsUploadStrategy.js
lib/prepareArchive.js
lib/proxy.js

https://github.com/mdyd-dev/pos-cli/issues/289

Direct upload: fixes packing and uploading assests

---

bin/pos-cli-data-import.js
bin/pos-cli-logs.js

https://github.com/mdyd-dev/desksnearme/issues/9182

Data import: add raw-ids option

---

bin/pos-cli-migrations-list.js

https://github.com/mdyd-dev/desksnearme/issues/9180
Oldest migration will be on top of the list.

Migration: list in the order returned by api

---

bin/pos-cli-logs.js

```pos-cli logs env``` will have context for each log entry.
There is a `--quiet` option that will print only lot message with timestamp.

Logs: add verbose mode to display context for each entry log

---

lib/archive.js
lib/deploy/directAssetsUploadStrategy.js
lib/files.js
test/deploy.test.js
test/fixtures/deploy/correct_only_assets/app/assets/foo.js
test/fixtures/deploy/correct_with_assets/app/assets/foo.js
test/fixtures/deploy/correct_with_assets/app/views/pages/hello.liquid
test/fixtures/deploy/correct_with_assets/modules/testModule/public/assets/bar.js
test/fixtures/deploy/correct_with_assets/modules/testModule/public/views/pages/hello-test-module.liquid
test/fixtures/deploy/correct_with_assets/modules/testModule/public/views/partials/dir/subdir/foo.liquid

- deploy mp without release files, only with assets
- deploy mp without modules dir
QA steps:
https://app.clickup.com/t/efkt7

Deploy: handle edge cases for direct assets deploying

---

lib/audit.js
lib/audit/fileName.js

Add filename check to only allow readable characters

---

bin/pos-cli-sync.js
lib/watch.js
npm-shrinkwrap.json
package.json

Add LiveReload support

---

lib/assets/manifest.js
lib/files.js
test/lib/assets/manifest.test.js

Fixes Matt problem from https://github.com/mdyd-dev/desksnearme/issues/9320

Fix assets manifest on windows

---

lib/audit/tags.js

Only detect the beginning of graphql queries on audit

---

bin/pos-cli-deploy.js
lib/assets.js
lib/deploy/defaultStrategy.js
lib/deploy/directAssetsUploadStrategy.js
lib/duration.js
lib/push.js
test/deploy.test.js

Fixes: https://github.com/mdyd-dev/desksnearme/issues/8860

Make direct upload default strategy for deploy

---

lib/assets/packAssets.js
lib/audit/detailed.js
lib/audit/duplicateFile.js
lib/audit/extensions.js
lib/audit/fileName.js
lib/audit/filters.js
lib/audit/tags.js
lib/files.js
npm-shrinkwrap.json
package.json

This should fix failing tests, originating from https://github.com/terkelg/tiny-glob/issues/28

Use fast glob instead of tiny-glob

---

lib/audit/orphanedIncludes.js
test/audit.test.js
test/fixtures/audit/orphanedIncludes_variable/app/views/pages/home.liquid
test/fixtures/audit/orphanedIncludes_variable/modules/test/private/views/pages/home.liquid

Fix variable include detection on orphaned include audit

---

bin/pos-cli-data-export.js
bin/pos-cli-data-import.js
lib/proxy.js

New CSV import export https://documentation.platformos.com/developer-guide/data-import-export/import#data-import-using-csv-files

Allow importing/exporting zip files

---

npm-shrinkwrap.json
package.json

Fixes https://github.com/mdyd-dev/pos-cli/issues/403

Update shelljs package

---

bin/pos-cli-data-import.js

Make it clear which file is being imported

Improve error reporting for file import

---

gui/liquid/public/index.html
lib/assets/packAssets.js
lib/proxy.js
lib/server.js

Fixes: https://github.com/mdyd-dev/desksnearme/issues/9422
Merge after backend PR: https://github.com/mdyd-dev/desksnearme/pull/9631

Liquid executor

---

bin/pos-cli-data-import.js
lib/presignUrl.js

We don't want to upload files directly into root s3 bucket, we need to put it into instance scope.

Data import: fix presign directory to be in instance scope

---

lib/ServerError.js
lib/proxy.js

Fixes https://github.com/mdyd-dev/pos-cli/issues/405

Exit on ENETDOWN

---

lib/push.js

Fixes https://github.com/mdyd-dev/pos-cli/issues/413

Use `warnings` returned by the server if deploy zip included unmatched files

---

lib/audit/orphanedIncludes.js
test/audit.test.js
test/fixtures/audit/orphanedIncludes/app/views/pages/home.liquid

Fixes https://github.com/mdyd-dev/pos-cli/issues/429

Support new liquid tag for included partials check

---

lib/audit/detailed.js

Fixes https://github.com/mdyd-dev/pos-cli/issues/410

Audit deprecated request headers

---

bin/pos-cli-env-add.js

Fixes: https://github.com/mdyd-dev/partner-portal/issues/1155

Improve message on wrong pass

---

bin/pos-cli-sync.js

Fixes: https://github.com/mdyd-dev/pos-cli/issues/452

Sync: make direct upload default strategy

---

lib/logger/report.js

This reverts commit ca6d9eb7fa5e1b4c2e76c55ba742aca81aefee13.

Revert "Split environments into buckets"

---

CHANGELOG.md
bin/pos-cli-archive.js
bin/pos-cli.js
lib/prepareArchive.js

```
pos-cli archive --output filename.zip
---

add-pos-cli-archive

---

bin/pos-cli-constants-list.js
bin/pos-cli-constants-set.js
bin/pos-cli-constants-unset.js
bin/pos-cli-constants.js
bin/pos-cli.js
lib/graph/queries.js

` pos-cli constants set --name xxxxx --value xXXXx`
` pos-cli constants unset --name xxxxx`
`pos-cli constants list`
```
ORDER_CANCEL_UNPAID_AFTER_X_HOURS                  "1..."
ORDER_MERCHANT_AUTO_CONFIRM                        "fa..."
ORDER_PAYMENT_LOCK_MINUTES                         "5..."
SECRETTOKEN                                        "XX..."
superadmins                                        "ad..."
TEMP_TOKEN                                         "XX..."
undefined                                          "[o..."
USE_SEARCH_INDEX                                   "tr..."
```
`SAFE=1 pos-cli constants list`
```
ORDER_CANCEL_UNPAID_AFTER_X_HOURS                  "1"
ORDER_MERCHANT_AUTO_CONFIRM                        "false"
ORDER_PAYMENT_LOCK_MINUTES                         "5" …
```

add pos-cli-constants

---

lib/shouldBeSynced.js

Fix for: https://near-me.atlassian.net/browse/NMS-5036?oldIssueView=true
Looks like we shouldn't attempt to sync template-values.json as it results in an error.
Thanks

Do not sync template values

---

lib/assets/manifest.js
test/lib/assets/manifest.test.js

Added file size to assets manifest
Thanks!

Add file size to assets manifest

---

README.md
bin/pos-cli-modules-init.js
bin/pos-cli-modules.js

Add a command to initialize a new module based on the module starter repository.

Add modules init command

---

bin/pos-cli-modules-version.js
bin/pos-cli-modules.js
lib/files.js
package-lock.json
package.json

https://trello.com/c/XoA7iOqC/46-versioning-in-modules

Module versioning

---

CHANGELOG.md
gui/next/src/lib/api/logs.js
package-lock.json
package.json

This reverts commit b23f8fdc38e76660b646ef8e5fa248097ea0175b.

Revert "Log message can be object (#513)"

---

.github/workflows/pull_requests.yml
gui/next/src/lib/api/logs.js

Followup to https://github.com/mdyd-dev/pos-cli/pull/520

Unhardcoded the logs api url

---

bin/pos-cli-modules-push.js
bin/pos-cli-modules-version.js
lib/files.js
lib/modules.js
lib/settings.js
lib/shouldBeSynced.js

https://trello.com/c/7aeYv5UO/75-convert-modules-directory-layout

Support unified module dir structure `modules/<module_name>/`

---

CHANGELOG.md
bin/pos-cli-modules-pull.js
lib/downloadFile.js
lib/unzip.js
package-lock.json
package.json

https://trello.com/c/QBGmuIeb/53-pos-cli-modules-pull-env-core

Fix modules pull

---

CHANGELOG.md
bin/pos-cli-modules-pull.js
bin/pos-cli-modules.js
lib/portal.js

https://trello.com/c/QBGmuIeb/53-pos-cli-modules-pull-env-core

Modules pull public package without env

---

lib/modules.js

https://github.com/mdyd-dev/pos-cli/issues/576

Skip `tmp/` directory when zipping release files for modules

---

CHANGELOG.md
README.md
bin/pos-cli-modules-download.js
bin/pos-cli-modules.js

https://trello.com/c/mLiMLz9k/105-fix-pos-cli-modules-pull

Add command modules download

---

lib/push.js
test/deploy.test.js

```
pos-cli deploy alp
Deploying to: https://getmarketplace-alpha.staging.oregon.platform-os.com/ 
[20:17:56] Deploy failed. StatusCodeError: 413 - "Request Entity Too Large"
pos-cli deploy stg
Deploying to: https://getmarketplace-beta.staging.oregon.platform-osx.com/ 
[20:23:44] Deploy failed. RequestError: Error: getaddrinfo ENOTFOUND getmarketplace-beta.staging.oregon.platform-osx.com
```

do-not-suppress-errors-on-deploy

---

package-lock.json
package.json

...to prevent some warnings during installation,

Updated uuid package

---

CHANGELOG.md
bin/pos-cli-modules-install.js
bin/pos-cli-modules-update.js
lib/modules/configFiles.js
lib/utils/create-directory.js

fixes #623 
Before:
After:
a) user invokes the command from the wrong directory and realizes it, does not want to proceed:
b) user does want to proceed

allow to install modules if app is missing

---

package-lock.json
package.json

Removed 'async' from deps

---

CHANGELOG.md
package-lock.json
package.json
test/deploy.test.js

`extract-zip` was used in tests but we already are using `unzipper` in pos-cli so replaced the modules in tests, few dependencies less.

Replace `extract-zip` with `unzipper`

---

CHANGELOG.md
lib/data/uploadFiles.js
package-lock.json
package.json

- 3 times faster
- No dependencies
- Node native

Replaced `uuid` node package with native Node UUID generator
